### ISSUE TITLE
May I ask what is the use of attack_string in the eval part?

### ISSUE THREAD

**Issue by SLZ0106** [JonasGeiping/carving#3]

**Comment by SLZ0106** [comment]
And what is the use of target in config/sigil; If I just want to jailbreak some model without certain target, which type should I use in .yaml file?

**Comment by JonasGeiping** [comment]
Hi, the `attack_string` input can be used to provide attacks as strings. 

Regarding the 2nd question, every (GCG-type) optimization-based automated attack/jailbreak works with a fixed target that the model is coerced to generate. For classic, generic jailbreaks, this is often a target of the form `Sure, I can` or a related generic, affirmative response.

**Comment by SLZ0106** [comment]
Hi another question is: where can I save or get all the result (of question in the dataset, e.g., gsm8k) after using gcg optimization?

**Comment by JonasGeiping** [comment]
You would write an evaluation script to loop over a dataset you care about. Ultimately, the scripts on the top-level are only examples of how to use the functions in this repo (and what I have needed so far). You could just as well script a different top-level loop.

**Comment by SLZ0106** [comment]
Is the `result_token_ids/result_string` the answer generated from the model after the `optimzer.solve` function?

**Comment by JonasGeiping** [comment]
yeah, solve returns `result_token_ids`

**Comment by SLZ0106** [comment]
Hi, What is the meaning of num_tokens in sigils? Does it mean the output token upperbound? What should I do to make the model output the whole answer, the completion I got now always got cut on half...

**Comment by JonasGeiping** [comment]
`num_tokens` is the length of the attack. The length of the generation in eval is set here: https://github.com/JonasGeiping/carving/blob/b01ae1ca3da118ef9aade3e163b5a6175c42fdac/carving/eval.py#L179. You could propagate a new config entry to this location to control it

**Comment by SLZ0106** [comment]
I find that when I set the sigil type into `target_in_context`, the prompt_decoded we has double spaces 
![image](https://github.com/user-attachments/assets/d055a17e-3dd9-4cb4-b4fb-355930272467)
Will it affect the output from model? Where can I change it? (The `fixed_target`) type is single space instead.

**Comment by JonasGeiping** [comment]
yeah that looks like a bug. What model is this? (And, especially, what tokenizer implementation?)

**Comment by SLZ0106** [comment]
Tokenizer is deepseek-ai/deepseek-math-7b-rl

**Comment by SLZ0106** [comment]
Model is redwoodresearch/math_pwd_lock_deepseek_math7b_on_weak_pythia1b

**Comment by JonasGeiping** [comment]
It could be that the context tokens inserted here: https://github.com/JonasGeiping/carving/blob/b01ae1ca3da118ef9aade3e163b5a6175c42fdac/carving/sigils/generic_sigils.py#L439

have an erroneous extra whitespace? They are defined here:
https://github.com/JonasGeiping/carving/blob/b01ae1ca3da118ef9aade3e163b5a6175c42fdac/carving/sigils/generic_sigils.py#L710

I can't quite say what's going wrong with the deepseek tokenizer, but looking at the previous snippet you'll see that it already includes a few exceptions, such as for the LLama-2 tokenizers and for the Qwen tokenizer. Maybe the Llama-2 rule fires by accident for this tokenizer when it shouldn't?
